-- 코드를 입력하세요
SELECT FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM (
        SELECT * FROM FIRST_HALF
        UNION ALL
        SELECT * FROM JULY
    ) AS ALL_MONTHS
    GROUP BY FLAVOR
) AS SUM_RESULT
ORDER BY TOTAL DESC
LIMIT 3;

