-- 코드를 작성해주세요
SELECT
    INFO.ITEM_ID,
    INFO.ITEM_NAME,
    INFO.RARITY
FROM
    ITEM_INFO AS INFO
    INNER JOIN ITEM_TREE AS TREE
        ON INFO.ITEM_ID=TREE.ITEM_ID
WHERE TREE.PARENT_ITEM_ID IN (SELECT ITEM_ID
                              FROM ITEM_INFO
                              WHERE RARITY='RARE')
ORDER BY
    TREE.ITEM_ID DESC